kind: pipeline
name: default
type: kubernetes

services:
- name: redis
  image: redis

steps:
- name: agent 1
  image: ruby:3.0
  commands: 
    - bundle install
    - KNAPSACK_PRO_CI_NODE_TOTAL=2 KNAPSACK_PRO_CI_NODE_INDEX=0 rspec
- name: agent 2
  image: ruby:3.0
  commands: 
    - bundle install
    - KNAPSACK_PRO_CI_NODE_TOTAL=2 KNAPSACK_PRO_CI_NODE_INDEX=1 rspec
    