kind: pipeline
name: default
type: kubernetes

services:
- name: redis
  image: redis

steps:
- name: agent_1
  image: ruby:3.0
  commands: 
    - bundle install
    - KNAPSACK_PRO_CI_NODE_TOTAL=2 KNAPSACK_PRO_CI_NODE_INDEX=0 rspec
- name: agent_2
  image: ruby:3.0
  commands: 
    - bundle install
    - KNAPSACK_PRO_CI_NODE_TOTAL=2 KNAPSACK_PRO_CI_NODE_INDEX=1 rspec
- name: data
  image: ruby:3.0
  commands: 
    - cat result.json
  depends_on: 
    - agent_1
    - agent_2